const textContent = [
  `My first week in Korea was a whirlwind of emotions and experiences. I arrived not knowing the language and sharing a room with three strangers, my roommates, whom I had met just a week prior. Initially, I felt quite alone and isolated, unable to understand anything around me. However, as the week went on, I bonded with my roommates over our shared awe and confusion of Korea. This photo captures my roommates, friends, and me at the Seoul National University International Student Orientation. This marks the beginning of my adventure.`,
  `Week 2 was very busy. Every day, my roommates and I were out and about exploring different parts of Seoul. One day, we wandered into Hongdae, a lively neighborhood known for its vibrant street art, indie music scene, and trendy cafes. This photo captures a moment of me feeding some cats at a local cat cafe in Hongdae. The cat cafe filled a small void in my heart as I’ve been missing my little puppy dog back home. Feeding and petting the cats reminded me a little bit of home and brought a sense of comfort and familiarity. It was nice to find a cozy spot amidst the hustle and bustle of the city where I could relax and connect with these furry friends. I enjoy these days of aimless wandering through parts of Seoul. It allows me to truly connect with the city.`,
  `Week 3 brought a dose of reality. The first few weeks had felt like a vacation of sorts, but now classes were in full swing, and I was settling into a routine. My roommates and I slowly stopped being tourists gawking at everything and soon became like everyone else, living our mundane lives. Part of that mundane life included grocery shopping. This photo shows a Costco in Korea, where one of my roommates and I went to stock up on food. This Costco was massive, with two floors and lots of free samples. Korean Costco is similar to American Costco, but instead of bulk American-branded foods and goods, it features Korean-branded items. I like Korean Costco.`,
  `On the weekends, my friends and I would explore more of the city as a break from classes. In this photo, we visited Namsan Seoul Tower, one of Seoul's most iconic landmarks. The tower offered breathtaking panoramic views of the city with a vibrant atmosphere. We took the cable car up to the tower and wandered around the observation deck, taking in the stunning scenery. One of the highlights was writing our names on the wall among countless others left by visitors from all over the world. It felt like leaving a small piece of ourselves in Korea, a testament to our time here. I hope to return someday and find my name again.`,
  `This photo is from my extended weekend getaway to Busan, South Korea's second-largest city and a popular coastal destination. Busan is a famous city in Korea known for its beautiful beaches, vibrant nightlife, and delicious seafood. I loved it there. The seafood was so good. My favorite dish was an octopus stew with intestines called "nakji bokkeum". I still think about it from time to time. Beyond the food, the company was even better. Some friends and family joined the trip. Their presence added an extra layer of joy and excitement to the trip, allowing for shared moments of discovery, and laughter, and creating lasting memories together.`,
  `While at SNU, I joined the SNU Buddy program, which pairs exchange students with Korean students to help them experience Korea. The goal is to help exchange students meet Korean buddies and enjoy fun activities in Korea. One highlight was the SNU Buddy Food Festival, where we created, tested, and served 100 servings of food representing a specific place. My housemates and I, along with a few friends, chose to serve Hawaiian cuisine. Our main dish was Loco Moco, a Hawaiian dish with a rice base, a beef patty, gravy, and a topped egg. We also served Spam Musubi and Hawaiian Blue Lemonade. The photo shows Team Hawaii serving food! The experience was exhausting but very rewarding. If you join the SNU Exchange program, I highly recommend participating in SNU Buddy!`,
  `Seoul is incredibly hilly, and I was not ready for any of it. Korea's landscape is much more mountainous than I had anticipated, and simply getting around campus and the city often involves steep climbs. One of the most memorable hikes I took was to the top of Gwanak Mountain, which SNU sits at the base of. The trek was challenging and my legs felt like noodles by the end of it but absolutely worth it. At the summit, there were two beautiful Buddhist temples, surrounded by a few stray cats.  This is a photo of me at the summit! The view from the top was breathtaking, offering a stunning panorama of Seoul below. The peacefulness and beauty of the temples, combined with the incredible view, made the hike an unforgettable experience.`,
  `I have a little dog named Blue at home. My family and I got her during the COVID-19 pandemic, and she has developed quite a bit of separation anxiety. Blue is my baby, and I missed her dearly while in Korea. One weekend, when I was feeling more homesick than usual, I visited a dog cafe to spend time with some furry, four-legged buddies. I went to a Samoyed dog cafe in Hongdae. All the dogs were extremely fluffy, friendly, and food-motivated. It was comforting to be around dogs and have a sense of home.`,
  `The trip to Sokcho was a bit of a last-minute adventure. Located in the northeast of Korea, Sokcho is a beach city renowned for its stunning natural beauty. My roommate, his sister who was visiting Korea, and I decided to go there on a whim, planning the trip only a day or so in advance. Due to our lack of planning, we couldn't secure a bus ticket, so we ended up renting a car—road trip time! In hindsight, renting the car was the perfect choice. It gave us much more freedom to explore the area around Sokcho, especially Seoraksan National Park. The hike there was definitely the highlight of the trip, with breathtaking views that made the journey worthwhile. Visiting Sokcho was a refreshing change from the bustling streets of Seoul.`,
  `BASEBALL GAME`,
  `SNU BUDDY MT GROUP PICS`,
  'JAPAN BREAK',
  `BIG GROUP MT`,
  `JEJU`,
  `FAREWELL DINNER`,
];

export default textContent;
